services:
  frontend:
    build: frontend/
    container_name: compus_fe
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - compus_net

networks:
  compus_net:
    driver: bridge


    