services:
  # backend:
  #   build: backend/
  #   container_name: compus_be
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydb
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=root
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./src:/app/src
  #     - ./target:/app/target
  #   networks:
  #     - compus_net

  # frontend:
  #   build: frontend/
  #   container_name: compus_fe
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend/src:/app/src
  #   networks:
  #     - compus_net

  db:
    image: postgres:13
    container_name: post_db
    restart: always
    environment:
      POSTGRES_USER: trails
      POSTGRES_PASSWORD: root
      POSTGRES_DB: compus
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - compus_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - compus_net
    
networks:
  compus_net:
    driver: bridge

volumes:
  pgdata: