services:
  # backend:
  #   build: backend/
  #   container_name: compus_be
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compus
  #     - SPRING_DATASOURCE_USERNAME=trails
  #     - SPRING_DATASOURCE_PASSWORD=root
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backend/src:/app/src
  #     - ./backend/target:/app/target
  #     - ./backend/.mvn:/root/.mvn
  #     - ./backend/.m2:/root/.m2
  #   networks:
  #     - compus_net

  # frontend:
  #   build: frontend/
  #   container_name: compus_fe
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend/src:/app/src
  #   networks:
  #     - compus_net

  db:
    image: postgis/postgis:13-3.4-alpine
    container_name: post_db
    restart: always
    environment:
      POSTGRES_USER: trails
      POSTGRES_PASSWORD: root
      POSTGRES_DB: compus
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - compus_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - compus_net

networks:
  compus_net:
    driver: bridge

volumes:
  pgdata: